# Site settings
title: Laura Ponce
email: lauraponce121103@gmail.com
url: https://lponce03.github.io/cyber-portfolio
description: "Portfolio of cybersecurity work samples for a entry-level cyber security professional."
keywords: "cybersecurity, cyber, security, portfolio, tech"
skills: "Cybersecurity - Analyst - Incident Response Specialist"
meta_author: Ponce Laura

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 9c86a3 #80B3FF
  primary-rgb: "156,134,163" #"128,179,255"
  secondary: 6f8268 #FD6E8A
  secondary-dark: 524557 #A2122F

# Footer settings
footer:
  copyright: Laura Ponce
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/laura-ponce-1203MP
  - title: github
    url: https://lponce03.github.io/cyber-portfolio

# Email Address (make sure to include "mailto:" before your email!)
email:
  email-url: mailto:lauraponce121103@gmail.com
# Postal address (add as many lines as necessary)
location:
  - line: Mcalester, Ok

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.
Cyber icons created by <a href="https://www.flaticon.com/free-icons/cyber-attack" title="cyber attack icons">Freepik - Flaticon</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
